@port = 3300

###
GET http://localhost:{{port}}/users

###
POST http://localhost:{{port}}/users
Content-Type: application/json

{
    "username":"jhon",
    "email":"jhon@gmail.com",
    "password":"222222",
    "hashedPassword":"",
    "role":"user"
}